version: '3.9' 
services:
  web:
    build: .
    command: uvicorn server.main:app --host 0.0.0.0 --port 5000
    ports:
      - 5000:5000
    env_file: 
      - .env
    restart: "on-failure"
    depends_on:
      - chroma
  chroma:
    build: ./chroma_db
    ports:
      - 8000:8000
    env_file: 
      - .env
    restart: "on-failure"